[tool.ruff]
line-length = 120

[tool.ruff.lint]

ignore = [
  "E501", # Never enforce `E501` (line length violations), which can be trivial.
  "G004", # Logging statement uses f-string
]
select = [
  "ALL"
]
pydocstyle.convention = "google"


# Ignore import violations in all `__init__.py` files.
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401", "F403", "F811"]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.isort]
profile = "black"
lines_after_imports = 2