# .github/workflows/update_holidays.yml
name: Atualização Anual de Feriados da ANBIMA

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 1 1 *"

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar script para baixar e processar feriados
        id: run_script
        run: |
          YEAR=$(python -c "from src.script import main; print(main())")
          echo "year=$YEAR" >> $GITHUB_OUTPUT

      - name: Fazer commit dos arquivos de dados
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'

          git add .

          if git diff --staged --quiet; then
            echo "Nenhuma mudança nos dados, commit não será realizado."
          else
            git commit -m "Atualização automática dos feriados para o ano de ${{ steps.run_script.outputs.year }}"
            git push
            echo "Novos dados de feriados e index.html foram commitados."
          fi
